--drop table student.test;
create table student.test(
    id  number generated by default as identity
    (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    sh_dt date default sysdate
);

create or replace procedure student.job_test_action
as
    --нет прагмы
begin
    insert into student.test(id)
    values (default);

    --нет коммита
end;
/

truncate table student.test;
