/**
  PARTITION
 */

--очистка таблицы
truncate table student.error_log;

--удаление таблицы
--режим purge для удаления и секций тоже,
--без него секции попадают в "мусорку" в oracle
drop table student.error_log purge;



/**
  MANUAL
 */

--создание таблицы сразу с секционированием
create table student.error_log(
    id_log number generated by default as identity
    (start with 1 maxvalue 9999999999999999999999999999 minvalue 1 nocycle nocache noorder) primary key,

    sh_user varchar2(50) default user,
    sh_dt date default sysdate,
    object_name varchar2(200),
    log_type varchar2(1000),
    params varchar2(4000)
)
partition by range (sh_dt) (
    partition part_1 values less than (to_date('19.11.2021 18:30', 'dd.mm.yyyy hh24:mi')),
    partition part_max values less than (maxvalue)
);



--где смотреть секции?
select * from sys.user_part_tables;
select * from sys.user_tab_partitions;



--очистка секции
alter table student.error_log truncate partition part_1;

--удаление секции
alter table student.error_log drop partition part_1;



--добавление секции через alter
--будет ORA-14074 если есть секция с maxvalue
alter table student.error_log
add partition part_2 values less than (to_date('19.11.2021 18:50', 'dd.mm.yyyy hh24:mi'));

--деление существующих секций
alter table student.error_log
split partition part_max at (to_date('19.11.2021 18:50', 'dd.mm.yyyy hh24:mi'))
into (partition part_2, partition part_max);



--пересборка индекса после пересоздания таблицы
alter index STUDENT.SYS_C0027720 rebuild;



--удалений секций оказавшихся в корзине изза drop без purge
purge table "BIN$0SN49QW7MRngVQJQVrZxLA==$0";



--нейминг и целесообразность
partition error_log_2021_qrt4 values less than (to_date('01.01.2022 00:00', 'dd.mm.yyyy hh24:mi'))
partition error_log_max values less than (maxvalue)



/**
  AUTO
 */

create table student.error_log(
    id_log number generated by default as identity
    (start with 1 maxvalue 9999999999999999999999999999 minvalue 1 nocycle nocache noorder) primary key,

    sh_user varchar2(50) default user,
    sh_dt date default sysdate,
    object_name varchar2(200),
    log_type varchar2(1000),
    params varchar2(4000)
)
partition by range (sh_dt)
interval (NUMTOYMINTERVAL(4, 'MONTH')) --YEAR, MONTH --"NUM TO YM INTERVAL"
--interval (NUMTODSINTERVAL(1, 'DAY')) --DAY, HOUR, MINUTE, SECOND --"NUM TO DS INTERVAL"
(
    partition error_log_2021_qrt4 values less than (to_date('01.01.2022 00:00', 'dd.mm.yyyy hh24:mi'))
);
